name: Sonar Cloud

on:
  push:
    branches:
      - staging
      - prod
  workflow_call:

env:
  # The SHA doesn't come from an intuitive place for push events: https://github.com/orgs/community/discussions/25191
  COMMIT_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}

jobs:
  getPrNumber:
    name: Get PR Number
    runs-on: ubuntu-latest
    outputs:
      prNumber: ${{ steps.get_pr_number.outputs.prNumber }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT";
          echo $GITHUB_CONTEXT | jq -r .number
          echo $GITHUB_CONTEXT | jq -r .event.pull_request.head.sha
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Show default environment variables
        run: |
          echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
          echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
          echo "The run id is: $GITHUB_RUN_ID"
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"
          echo "GitHub SHA: $GITHUB_SHA"
          echo "COMMIT_SHA: $COMMIT_SHA"
      # - name: Download coverage artifacts
      #   uses: actions/download-artifact@v4.1.1
      #   with:
      #     run-id: ${{ github.event.workflow_run.id }}
      #     github-token: ${{ github.token }}
      #     name: code-coverage-reports
      - name: Get PR Number Associated With Commit
        id: get_pr_number
        run: |
          prNumber=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/rivial-data-security/rivial-information-security-center/commits/$COMMIT_SHA/pulls | jq -r '.[0].number');
            echo "prNumber=${prNumber}" >> "$GITHUB_OUTPUT"
      - name: setup env variable
        run: echo "PR Number for SHA '$COMMIT_SHA' is '$prNumber'"
        env:
          PR_NUMBER: ${{ steps.get_pr_number.outputs.prNumber }}
  sonarcloud:
    needs: getPrNumber
    name: Sonar Cloud
    runs-on: ubuntu-latest
    steps:
      - name: setup env variable
        run: echo "🚀🚀🚀 env variable is ${{ needs.getPrNumber.outputs.prNumber }}"
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Fetch Archive of Code Coverage Results
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: jest.yml
          workflow_conclusion: in_progress
          pr: ${{ needs.getPrNumber.outputs.prNumber }}
          name: code-coverage-reports
